export enum Language {
    javascript = "JavaScript",
    typescript = "TypeScript",
    python = "Python",
    go = "Go",
    rust = "Rust",
    c = "C",
    cpp = "C++",
    csharp = "C#",
    java = "Java",
    php = "PHP",
    ruby = "Ruby",
    swift = "Swift",
    kotlin = "Kotlin",
    scala = "Scala",
    html = "HTML",
    css = "CSS",
    scss = "SCSS",
    json = "JSON",
    xml = "XML",
    yaml = "YAML",
    markdown = "Markdown",
    sql = "SQL",
    shell = "Shell",
    powershell = "PowerShell",
    dockerfile = "Dockerfile",
    plaintext = "Plaintext",
}